// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {query} from '../models';

export function GetAlbumTracks(arg1:string):Promise<Array<models.Track>>;

export function GetAlbums(arg1:number,arg2:number):Promise<query.PaginatedAlbums>;

export function GetRandomAlbum(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function ScanMusic(arg1:string):Promise<void>;
