// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {query} from '../models';

export function GetAlbumTracks(arg1:string):Promise<Array<models.Track>>;

export function GetAlbums(arg1:number,arg2:number):Promise<query.PaginatedAlbums>;

export function GetFacets(arg1:string):Promise<Record<string, Array<query.Facet>>>;

export function GetFilteredAlbums(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<query.PaginatedAlbums>;

export function GetRandomAlbum(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function ScanMusic(arg1:string):Promise<void>;
