// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlbumTracks(arg1) {
  return window['go']['main']['App']['GetAlbumTracks'](arg1);
}

export function GetAlbums(arg1, arg2) {
  return window['go']['main']['App']['GetAlbums'](arg1, arg2);
}

export function GetFacets(arg1) {
  return window['go']['main']['App']['GetFacets'](arg1);
}

export function GetFilteredAlbums(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetFilteredAlbums'](arg1, arg2, arg3, arg4, arg5);
}

export function GetRandomAlbum(arg1) {
  return window['go']['main']['App']['GetRandomAlbum'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function ReScanMarked(arg1) {
  return window['go']['main']['App']['ReScanMarked'](arg1);
}

export function ScanMusic(arg1) {
  return window['go']['main']['App']['ScanMusic'](arg1);
}
